### ISSUE TITLE
`docpad run` shows errors

### ISSUE THREAD

**Issue by morenoh149** [Semantic-Org/Semantic-UI-Docs#223]
I get the following
```bash
➞  docpad run                                                                                                                                                                        [git:master] ✔ []
info: Welcome to DocPad v6.78.6 (global installation: /Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad)
notice: Please donate to DocPad or have your company sponsor it: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: 
info: Environment: development
info: Server started on http://0.0.0.0:9778
info: In your web browser use http://127.0.0.1:9778
undefined
notice: DocPad is currently running without any plugins installed. You probably want to install some: http://docpad.org/plugins
info: Generating...
warning: A warning occured:

Error: Rendering the extension "eco" to "html" on "/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/server/documents/404.html.eco" didn't do anything.
Explanation here: http://docpad.org/extension-not-rendering
  at DocPad.warn (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/out/lib/docpad.js:3541:50)
  at DocumentModel.<anonymous> (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/out/lib/docpad.js:3901:20)
  at triggerEvents (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/backbone/backbone.js:370:57)
  at triggerApi (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/backbone/backbone.js:356:19)
  at eventsApi (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/backbone/backbone.js:155:16)
  at DocumentModel.Events.trigger (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/backbone/backbone.js:346:5)
  at DocumentModel.emit (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/out/lib/base.js:23:23)
  at DocumentModel.log (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/out/lib/base.js:16:13)
  at /Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/out/lib/models/document.js:533:18
  at TaskGroup.<anonymous> (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/out/lib/docpad.js:2204:14)
  at TaskGroup.g (events.js:260:16)
  at emitTwo (events.js:87:13)
  at TaskGroup.emit (events.js:172:7)
  at TaskGroup.<anonymous> (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:53:28)
  at emitTwo (events.js:87:13)
  at TaskGroup.emit (events.js:172:7)
  at TaskGroup.complete (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:972:14)
  at TaskGroup.exit (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:1116:12)
  at TaskGroup.fire (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:1074:16)
  at TaskGroup.itemCompletionCallback (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:1067:12)
  at Task.<anonymous> (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:766:42)
  at Task.g (events.js:260:16)
  at emitNone (events.js:72:20)
  at Task.emit (events.js:166:7)
  at Task.<anonymous> (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:53:28)
  at emitNone (events.js:72:20)
  at Task.emit (events.js:166:7)
  at Task.complete (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:319:19)
  at Task.exit (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:301:14)
  at complete (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:388:26)
  at DocPad.<anonymous> (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/out/lib/docpad.js:1994:18)
  at ambi (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/event-emitter-grouped/node_modules/ambi/out/lib/ambi.js:55:18)
  at Task.<anonymous> (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/event-emitter-grouped/out/lib/event-emitter-grouped.js:45:23)
  at ambi (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/ambi/es2015/index.js:97:14)
  at Domain.fireMethod (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:397:23)
  at Domain.run (domain.js:228:14)
  at Task.fire (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:435:27)
  at Immediate._onImmediate (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:452:26)
  at processImmediate [as _immediateCallback] (timers.js:383:17)

To report the above, follow the guide at: http://docpad.org/bug-report
warning: A warning occured:

Error: Rendering the extension "eco" to "html" on "/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/server/documents/cla.html.eco" didn't do anything.
Explanation here: http://docpad.org/extension-not-rendering
  at DocPad.warn (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/out/lib/docpad.js:3541:50)
  at DocumentModel.<anonymous> (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/out/lib/docpad.js:3901:20)
  at triggerEvents (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/backbone/backbone.js:370:57)
  at triggerApi (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/backbone/backbone.js:356:19)
  at eventsApi (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/backbone/backbone.js:155:16)
  at DocumentModel.Events.trigger (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/backbone/backbone.js:346:5)
  at DocumentModel.emit (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/out/lib/base.js:23:23)
  at DocumentModel.log (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/out/lib/base.js:16:13)
  at /Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/out/lib/models/document.js:533:18
  at TaskGroup.<anonymous> (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/out/lib/docpad.js:2204:14)
  at TaskGroup.g (events.js:260:16)
  at emitTwo (events.js:87:13)
  at TaskGroup.emit (events.js:172:7)
  at TaskGroup.<anonymous> (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:53:28)
  at emitTwo (events.js:87:13)
  at TaskGroup.emit (events.js:172:7)
  at TaskGroup.complete (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:972:14)
  at TaskGroup.exit (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:1116:12)
  at TaskGroup.fire (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:1074:16)
  at TaskGroup.itemCompletionCallback (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:1067:12)
  at Task.<anonymous> (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:766:42)
  at Task.g (events.js:260:16)
  at emitNone (events.js:72:20)
  at Task.emit (events.js:166:7)
  at Task.<anonymous> (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:53:28)
  at emitNone (events.js:72:20)
  at Task.emit (events.js:166:7)
  at Task.complete (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:319:19)
  at Task.exit (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:301:14)
  at complete (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:388:26)
  at DocPad.<anonymous> (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/out/lib/docpad.js:1994:18)
  at ambi (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/event-emitter-grouped/node_modules/ambi/out/lib/ambi.js:55:18)
  at Task.<anonymous> (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/event-emitter-grouped/out/lib/event-emitter-grouped.js:45:23)
  at ambi (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/ambi/es2015/index.js:97:14)
  at Domain.fireMethod (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:397:23)
  at Domain.run (domain.js:228:14)
  at Task.fire (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:435:27)
  at Immediate._onImmediate (/Users/harrymoreno/.nvm/versions/node/v5.4.0/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:452:26)
  at processImmediate [as _immediateCallback] (timers.js:383:17)

To report the above, follow the guide at: http://docpad.org/bug-report

...
```
The last error repeats dozens of times. Also when I open `127.0.0.1:9778` in a browser I get the following text
```html
<%- @partial('meta') %> <%- @partial('css') %> <%- @partial('tracking') %> <%- @partial('sidebar') %> <%- @partial('fixed-menu') %>
<%- @content %>
<%- @partial('footer') %>
<%- @partial('language-modal') %> <% if 'development' in @getEnvironments(): %> <% else: %> <% end %> <%- @partial('transifex') %> <%- @partial('ui-javascript') %> <%- @partial('less') %>
```

thoughts?

**Comment by eliaaas** [comment]
Stop this fucking spam messages! 😡

**Comment by morenoh149** [comment]
@eliaaas you should figure out how to unsubscribe from github emails.

**Comment by morenoh149** [comment]
running `docpad install eco` (again) seems to fix it. odd.
