### ISSUE TITLE
How to export docs as a static website?

### ISSUE THREAD

**Issue by morenoh149** [Semantic-Org/Semantic-UI-Docs#225]
So I'm able to run the docs site locally with the docpad webserver. Is there anyway to export the site as a collection of static files?

I tried `docpad generate --env static` as detailed [here](http://docpad.org/docs/deploy/) but I get the following error
```bash
❯ docpad generate --env static
info: Welcome to DocPad v6.78.6 (local installation: /Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/docpad)
notice: Please donate to DocPad or have your company sponsor it: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: copy, eco, ghpages, partials
info: Environment: static
info: Generating...

Error: Rendering the extension "eco" to "html" on "/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/server/documents/hotfix.html.eco" didn't do anything.
Explanation here: http://docpad.org/extension-not-rendering
  at DocPad.warn (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/docpad/out/lib/docpad.js:3541:50)
  at DocumentModel.<anonymous> (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/docpad/out/lib/docpad.js:3901:20)
  at triggerEvents (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/backbone/backbone.js:370:57)
  at triggerApi (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/backbone/backbone.js:356:19)
  at eventsApi (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/backbone/backbone.js:155:16)
  at DocumentModel.Events.trigger (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/backbone/backbone.js:346:5)
  at DocumentModel.emit (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/docpad/out/lib/base.js:23:23)
  at DocumentModel.log (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/docpad/out/lib/base.js:16:13)
  at /Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/docpad/out/lib/models/document.js:533:18
  at TaskGroup.<anonymous> (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/docpad/out/lib/docpad.js:2204:14)
  at TaskGroup.g (events.js:260:16)
  at emitTwo (events.js:87:13)
  at TaskGroup.emit (events.js:172:7)
  at TaskGroup.<anonymous> (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/taskgroup/out/lib/taskgroup.js:53:28)
  at emitTwo (events.js:87:13)
  at TaskGroup.emit (events.js:172:7)
  at TaskGroup.complete (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/taskgroup/out/lib/taskgroup.js:972:14)
  at TaskGroup.exit (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/taskgroup/out/lib/taskgroup.js:1116:12)
  at TaskGroup.fire (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/taskgroup/out/lib/taskgroup.js:1074:16)
  at TaskGroup.itemCompletionCallback (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/taskgroup/out/lib/taskgroup.js:1067:12)
  at Task.<anonymous> (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/taskgroup/out/lib/taskgroup.js:766:42)
  at Task.g (events.js:260:16)
  at emitNone (events.js:72:20)
  at Task.emit (events.js:166:7)
  at Task.<anonymous> (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/taskgroup/out/lib/taskgroup.js:53:28)
  at emitNone (events.js:72:20)
  at Task.emit (events.js:166:7)
  at Task.complete (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/taskgroup/out/lib/taskgroup.js:319:19)
  at Task.exit (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/taskgroup/out/lib/taskgroup.js:301:14)
  at complete (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/taskgroup/out/lib/taskgroup.js:388:26)
  at DocPad.<anonymous> (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/docpad/out/lib/docpad.js:1994:18)
  at ambi (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/event-emitter-grouped/node_modules/ambi/out/lib/ambi.js:55:18)
  at Task.<anonymous> (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/event-emitter-grouped/out/lib/event-emitter-grouped.js:45:23)
  at ambi (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/ambi/es2015/index.js:97:14)
  at Domain.fireMethod (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/taskgroup/out/lib/taskgroup.js:397:23)
  at Domain.run (domain.js:228:14)
  at Task.fire (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/taskgroup/out/lib/taskgroup.js:435:27)
  at Immediate._onImmediate (/Users/harrymoreno/Code/src/github.com/CapsuleHealth/docs/node_modules/taskgroup/out/lib/taskgroup.js:452:26)
  at processImmediate [as _immediateCallback] (timers.js:383:17)

To report the above, follow the guide at: http://docpad.org/bug-report
```

this is after running `gulp build-docs` from the `ui/` directory and executing the above inside the `doc/` directory. I'm certain `docpad install eco` has been run and is working as I'm able to run the webserver, but I want to export the site as a collection of staticfiles. Thoughts?

**Comment by jlukic** [comment]
That is a standard warning for any file named `html.eco` that doesnt use `eco`. There's a file `hotfix.html.eco` that I sometimes use to debug test cases that might cause that warning.

You can fix prevent the warning by removing `hotfix.html.eco` from your files.

In either case, the files should still be generated if you check.
